---
# tasks file for role/server_1
- name: Ensure the user exists
  ansible.builtin.user:
    name: "{{ target_user }}"
    state: present
    shell: /bin/bash
    create_home: yes

- name: Grant sudo privileges to the user
  ansible.builtin.copy:
    dest: /etc/sudoers.d/{{ target_user }}
    content: "{{ target_user }} ALL=(ALL) NOPASSWD:ALL"
    owner: root
    group: root
    mode: '0440'

- name: Disable password authentication for SSH
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
    backup: yes

- name: Restart SSH service
  ansible.builtin.service:
    name: sshd
    state: restarted
    enabled: yes

- name: Add SSH public key for user
  copy:
    content: "{{ ssh_public_key }}"
    dest: /home/{{ target_user }}/.ssh/authorized_keys
    mode: '0600'
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
